# Generated by Django 5.1 on 2024-08-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0004_alter_recipe_id_alter_recipebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='id',
            field=models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
