# Generated by Django 5.1 on 2024-08-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0005_alter_recipebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
