# Generated by Django 5.1 on 2024-08-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0007_recipe_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='summary',
        ),
    ]
